---
title: "Admissions Analysis"
author: "Daniel O'Leary"
date: "4/17/2020"
output: 
  github_document:
    toc: true
---

# Setup

## Load Packages
```{r setup, include=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse)
```


## Load Data

```{r load data, warning = FALSE}
eth <- 
  read_csv("C:/Users/Daniel/OneDrive - Leland Stanford Junior University/dc/applicant_analysis/applicant_analysis/results/eth_summaries.csv") 

gender <- 
  read_csv("C:/Users/Daniel/OneDrive - Leland Stanford Junior University/dc/applicant_analysis/applicant_analysis/results/gender.csv") 

n_applicants <- 
  read_csv("C:/Users/Daniel/OneDrive - Leland Stanford Junior University/dc/applicant_analysis/applicant_analysis/results/n_applicants.csv") 

eth <-
  eth %>% 
  mutate(eth = X1) %>% 
  dplyr::select(-X1)

gender <-
  gender %>% 
  mutate(area = X1) %>% 
  dplyr::select(-X1)

n_applicants <-
  n_applicants %>% 
  mutate(area = X1) %>% 
  dplyr::select(-X1)
```

# Analysis

## Total number of apps by area

### Counts from eth_summaries

```{r}
eth %>% 
  gather(area, value, Affective:Social) %>% 
  count(area, season, wt = value) %>% 
  mutate(
    total_apps = n
  ) %>% 
  dplyr::select(-c(n)) %>% 
  arrange(season)
```

### Counts from n_applicants file

```{r}
n_applicants %>% 
  gather(season, total_apps, `2017-18`:`2019-20`)
```